# Generated by Django 5.1.7 on 2025-06-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Godwin Uche I.", max_length=100),
        ),
    ]
