# Generated by Django 5.1.7 on 2025-06-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Godwin", max_length=100),
        ),
    ]
