# Generated by Django 5.1.7 on 2025-06-17 12:19

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="blog_images/",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
